# 5972d798b67cba9bb388ffd1bfde14b91fd635a9 encoding: utf-8
# @@ 1

########################### DO NOT MODIFY THIS FILE ###########################
#       This file was automatically generated by JRubyFX-fxmlloader on        #
# 2016-01-06 20:19:15 -0500 for ../sfx/plugins/built-in/bool/BadBool.fxml
########################### DO NOT MODIFY THIS FILE ###########################

module JRubyFX
  module GeneratedAssets
    class AOT774a63170b63edbd5e88db7126df6db9645b436c
      include JRubyFX
          def __build_via_jit(__local_fxml_controller, __local_namespace, __local_jruby_ext)
      __local_fx_id_setter = lambda do |name, __i|
        __local_namespace[name] = __i
        __local_fxml_controller.instance_variable_set(("@#{name}").to_sym, __i)
      end
(__local_sem_inst = Java.javax.script.ScriptEngineManager.new).setBindings(javax.script.SimpleBindings.new(__local_namespace))
(__local_sem_lang_inst_javascript = __local_sem_inst.getEngineByName("javascript")).setBindings(__local_sem_inst.getBindings(), javax.script.ScriptContext.ENGINE_SCOPE)
build(Java::DashfxControlsBases::BooleanControlBase) do
 __local_fx_id_setter.call("base", self)
 __local_jruby_ext[:on_root_set].call(self) if __local_jruby_ext[:on_root_set]
 __local_sem_lang_inst_javascript.eval("\n\t\tfunction moused(e)\n\t\t{\n\t\t\tbase.setValue(!base.getValue());\n\t\t}\n\t")
 setUi(build(Java::JavafxSceneLayout::HBox) do
  getChildren.add(build(Java::JavafxSceneLayout::StackPane) do
   getChildren.add(build(Java::JavafxSceneLayout::StackPane) do
    setPrefHeight(16.0)
    setPrefWidth(16.0)
    setStyle("-fx-background-color: #60dc00;")
    visibleProperty.bind(RRExpressionValue.new(__local_namespace, Java::org.jruby.jfx8.Expression.valueOf("base.value"), Java::boolean.java_class))
   end)
   setPrefHeight(-1.0)
   setPrefWidth(-1.0)
   setStyle("-fx-background-color: #df0040;")
   Java::JavafxSceneLayout::HBox.setHgrow(self, Java::javafx::scene::layout::Priority::ALWAYS)
  end)
  setAlignment(Java::javafx::geometry::Pos::CENTER_LEFT)
  setPrefHeight(-1.0)
  setPrefWidth(-1.0)
  setOnMouseClicked(ScriptEventHandler.new("moused(event)", __local_sem_lang_inst_javascript))
 end)
end
    end

      def hash
        "5972d798b67cba9bb388ffd1bfde14b91fd635a9"
      end
      def compiled?
        true
      end
    end
  end
end
