/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_wpi_cscore_CameraServerJNI */

#ifndef _Included_edu_wpi_cscore_CameraServerJNI
#define _Included_edu_wpi_cscore_CameraServerJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getPropertyKind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getPropertyKind
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getPropertyName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getPropertyName
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getProperty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getProperty
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setProperty
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setProperty
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getPropertyMin
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getPropertyMin
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getPropertyMax
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getPropertyMax
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getPropertyStep
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getPropertyStep
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getPropertyDefault
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getPropertyDefault
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getStringProperty
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getStringProperty
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setStringProperty
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setStringProperty
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getEnumPropertyChoices
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_getEnumPropertyChoices
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createUsbCameraDev
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createUsbCameraDev
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createUsbCameraPath
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createUsbCameraPath
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createHttpCamera
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createHttpCamera
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createHttpCameraMulti
 * Signature: (Ljava/lang/String;[Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createHttpCameraMulti
  (JNIEnv *, jclass, jstring, jobjectArray, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createCvSource
 * Signature: (Ljava/lang/String;IIII)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createCvSource
  (JNIEnv *, jclass, jstring, jint, jint, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSourceKind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSourceKind
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSourceName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSourceName
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSourceDescription
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSourceDescription
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSourceLastFrameTime
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSourceLastFrameTime
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    isSourceConnected
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_cscore_CameraServerJNI_isSourceConnected
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSourceProperty
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSourceProperty
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    enumerateSourceProperties
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_enumerateSourceProperties
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSourceVideoMode
 * Signature: (I)Ledu/wpi/cscore/VideoMode;
 */
JNIEXPORT jobject JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSourceVideoMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourceVideoMode
 * Signature: (IIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourceVideoMode
  (JNIEnv *, jclass, jint, jint, jint, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourcePixelFormat
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourcePixelFormat
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourceResolution
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourceResolution
  (JNIEnv *, jclass, jint, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourceFPS
 * Signature: (II)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourceFPS
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    enumerateSourceVideoModes
 * Signature: (I)[Ledu/wpi/cscore/VideoMode;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_enumerateSourceVideoModes
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    enumerateSourceSinks
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_enumerateSourceSinks
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    copySource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_copySource
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    releaseSource
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_releaseSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraBrightness
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraBrightness
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getCameraBrightness
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getCameraBrightness
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraWhiteBalanceAuto
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraWhiteBalanceAuto
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraWhiteBalanceHoldCurrent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraWhiteBalanceHoldCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraWhiteBalanceManual
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraWhiteBalanceManual
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraExposureAuto
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraExposureAuto
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraExposureHoldCurrent
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraExposureHoldCurrent
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setCameraExposureManual
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setCameraExposureManual
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getUsbCameraPath
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getUsbCameraPath
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getHttpCameraKind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getHttpCameraKind
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setHttpCameraUrls
 * Signature: (I[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setHttpCameraUrls
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getHttpCameraUrls
 * Signature: (I)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_getHttpCameraUrls
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    putSourceFrame
 * Signature: (IJ)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_putSourceFrame
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    notifySourceError
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_notifySourceError
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourceConnected
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourceConnected
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourceDescription
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourceDescription
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createSourceProperty
 * Signature: (ILjava/lang/String;IIIIII)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createSourceProperty
  (JNIEnv *, jclass, jint, jstring, jint, jint, jint, jint, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSourceEnumPropertyChoices
 * Signature: (II[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSourceEnumPropertyChoices
  (JNIEnv *, jclass, jint, jint, jobjectArray);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createMjpegServer
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createMjpegServer
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    createCvSink
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_createCvSink
  (JNIEnv *, jclass, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSinkKind
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSinkKind
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSinkName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSinkName
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSinkDescription
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSinkDescription
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSinkSource
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSinkSource
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSinkSourceProperty
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSinkSourceProperty
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSinkSource
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSinkSource
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    copySink
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_copySink
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    releaseSink
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_releaseSink
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getMjpegServerListenAddress
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getMjpegServerListenAddress
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getMjpegServerPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_getMjpegServerPort
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSinkDescription
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSinkDescription
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    grabSinkFrame
 * Signature: (IJ)J
 */
JNIEXPORT jlong JNICALL Java_edu_wpi_cscore_CameraServerJNI_grabSinkFrame
  (JNIEnv *, jclass, jint, jlong);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getSinkError
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getSinkError
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setSinkEnabled
 * Signature: (IZ)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setSinkEnabled
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    addListener
 * Signature: (Ljava/util/function/Consumer;IZ)I
 */
JNIEXPORT jint JNICALL Java_edu_wpi_cscore_CameraServerJNI_addListener
  (JNIEnv *, jclass, jobject, jint, jboolean);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    removeListener
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_removeListener
  (JNIEnv *, jclass, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    setLogger
 * Signature: (Ledu/wpi/cscore/CameraServerJNI/LoggerFunction;I)V
 */
JNIEXPORT void JNICALL Java_edu_wpi_cscore_CameraServerJNI_setLogger
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    enumerateUsbCameras
 * Signature: ()[Ledu/wpi/cscore/UsbCameraInfo;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_enumerateUsbCameras
  (JNIEnv *, jclass);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    enumerateSources
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_enumerateSources
  (JNIEnv *, jclass);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    enumerateSinks
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_enumerateSinks
  (JNIEnv *, jclass);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getHostname
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_edu_wpi_cscore_CameraServerJNI_getHostname
  (JNIEnv *, jclass);

/*
 * Class:     edu_wpi_cscore_CameraServerJNI
 * Method:    getNetworkInterfaces
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_edu_wpi_cscore_CameraServerJNI_getNetworkInterfaces
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
